version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: amamov
      POSTGRES_USER: 'amamov'
      POSTGRES_PASSWORD: '1205'
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: me@amamov.com
      PGADMIN_DEFAULT_PASSWORD: '1205'
    ports:
      - 5555:80
    depends_on:
      - db
